[package]
name = "challenges"
description = "A collection of coding challenges."
repository = "https://github.com/lukehsiao/code-challenges"
homepage = "https://challenge.hsiao.dev"
license = "BlueOak-1.0.0"
version = "0.1.0"
edition = "2021"
rust-version = "1.69"
publish = false

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
axum = { version = "0.6.18", features = ["http2"] }
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
config = { version = "0.13.3", features = ["toml"] }
hyper = { version = "0.14.27", features = ["full"] }
once_cell = "1.18.0"
rand = { version = "0.8.5", features = ["std_rng"] }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.168", features = ["derive"] }
serde-aux = "4.2.0"
serde_json = "1.0.103"
sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "sqlite", "chrono", "offline"] }
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.4.1", features = ["trace", "compression-full", "request-id", "util"] }
tracing = "0.1.37"
tracing-bunyan-formatter = "0.3.7"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "registry", "fmt"] }
uuid = { version = "1.4.0", features = ["v4", "serde"] }

[dev-dependencies]
futures = "0.3.28"
mime = "0.3.17"
pretty_assertions = "1.4.0"
reqwest = { version = "0.11.18", default-features = false, features = ["json", "rustls-tls", "cookies"] }
tempfile = "3.6.0"
wiremock = "0.5.19"

[[example]]
name = "passwords"
path = "examples/passwords/main.rs"
