[package]
name = "hsiao-challenge"
version = "0.1.0"
authors = ["Luke Hsiao <luke@hsiao.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
data-encoding = "2.3.1"
rocket = "0.4.6"
rocket_contrib = "0.4.6"
sha2 = "0.9.2"
