[package]
name = "challenges"
description = "A collection of coding challenges."
repository = "https://github.com/lukehsiao/code-challenges"
homepage = "https://challenge.hsiao.dev"
license = "BlueOak-1.0.0"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
publish = false

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["tokio", "http2"] }
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
config = { version = "0.14.0", features = ["toml"] }
hyper = { version = "1.3.1", features = ["full"] }
once_cell = "1.19.0"
rand = { version = "0.8.5", features = ["std_rng"] }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.203", features = ["derive"] }
serde-aux = "4.5.0"
serde_json = "1.0.117"
sqlx = { version = "0.7.4", features = ["runtime-tokio-rustls", "sqlite", "chrono"] }
thiserror = "1.0.63"
tokio = { version = "1.38.0", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.5.2", features = ["trace", "compression-full", "request-id", "util"] }
tracing = "0.1.40"
tracing-bunyan-formatter = "0.3.9"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "registry", "fmt"] }
uuid = { version = "1.8.0", features = ["v4", "serde"] }

[dev-dependencies]
futures = "0.3.30"
mime = "0.3.17"
pretty_assertions = "1.4.0"
reqwest = { version = "0.11.27", default-features = false, features = ["json", "rustls-tls", "cookies"] }
tempfile = "3.10.1"
wiremock = "0.6.0"

[[example]]
name = "passwords"
path = "examples/passwords/main.rs"
